### ISSUE TITLE
Listing sites that don’t behave nicely

### ISSUE THREAD

**Issue by lnikkila** [lnikkila/chrome-panel-tabs#11]
Which sites would you like to use with Panel Tabs but won’t behave nicely?

- YouTube
- Vimeo
- Twitter
- Fox video player
- CNN video player
- Adult Swim video player
- Wikipedia

Leave a reply below! You can also attach a screen shot.

**Comment by F0rfrey** [comment]
Vulcun.com. It worked just flawless, but for no reason known to me it stopped to work properly.
This is a comparison screen of how it looks in the web browser (and how it did look in the panel before also) and how it looks in the panel. http://imgur.com/TeRt1ZV
Basically, what you can see in the panel, is the mobile version of the website. Therefore flash player is cut off the site, and it's actually the most important thing. I've reinstalled Panel Tabs, I've cleaned cache of my web browser - none of those helped.

**Comment by lnikkila** [comment]
Looks like that site changed its design to a more responsive one. It changes to the mobile look when the browser window is narrow enough; you can try it out in a regular window by resizing it to be narrower until you see the layout switch.

Unfortunately there’s not much the extension can do here. You could try contacting the site and telling them that their player is cut off in the mobile look, hopefully they will fix it.
