### ISSUE TITLE
Automatically minimising panels

### ISSUE THREAD

**Issue by dannyhope** [lnikkila/chrome-panel-tabs#15]
Sometimes I want panels to behave like system menus (File, Edit etc.) in that blurring them minimises them. Doing email, is a good example.

Other times I want them to stay on top. Youtube is a good example.

There’s a conflict here and I have no simple solution.

Non simple solutions
- something like Chrome’s "Pin tab" – I think people would overlook this
- a "Automatically minimise panels" setting in the browser button popup – offloading the decision to the user

Despite my lack of good suggestions, I thought I should open the issue for discussion.

**Comment by lnikkila** [comment]
Do you often run into a situation where you’d like to have automatically collapsing panels but at the same time keep some of them open? A simple setting wouldn’t probably work in that situation.

I’m not yet sure if this feasible either; I need to check if Chrome implements the “minimised” state for panels correctly. Some parts of the panels API are still a bit patchy.

**Comment by dannyhope** [comment]
> Do you often run into a situation where you’d like to have automatically collapsing panels but at the same time keep some of them open? A simple setting wouldn’t probably work in that situation.

I do: Inbox and Youtube. I agree a "Close blurred panels" setting would be pretty much a non-solution.

The inability to add a "pin" or "keep on top" control per window leaves us a bit stuck.

Anecdotally, I use [Fluid](http://fluidapp.com "") single site browsers with Fluid’s "Pin to Status Bar" feture. I see these as comparable to panels. These apps automatically close on blur andI rarely find it to be a problem. That said I’ve never tried to watch video in any of them.

**Comment by lnikkila** [comment]
I wrote a version that automatically collapses panels. It’s just a quick test—it doesn’t have a way to control that behaviour, but it’d be great if you could try it out and tell me how it feels.

[The packaged build](https://drive.google.com/file/d/0B9UscY63JkymcXRBZENtSnlwaFU/view?usp=sharing) has a different signature. When you install it (by dragging and dropping it to chrome://extensions) it gets installed alongside the stable release.

**Comment by dannyhope** [comment]
I’ve switched to that version and will let you know I get on. It already feels nice when doing email.

**Comment by lnikkila** [comment]
Great, thanks! :+1:

**Comment by dannyhope** [comment]
I’ve now been using the automatically collapsing version for a week and
definitely prefer it.

–My 2p

**Comment by lnikkila** [comment]
Nice. The next release will add some behaviour-related settings and it will be possible to control this as well. Pinning tabs should be available in the release after that. Thanks for testing!

**Comment by lnikkila** [comment]
I was thinking that pinning could be implemented elegantly by using Chrome’s own pinning feature. Here’s how it could work:

- If a page is pinned in a regular tab, then that page will also stay open in a panel.

- If automatic collapsing is enabled, the extension popup could also accommodate a pin toggle for each panel next to the favicon. This would essentially toggle Chrome’s own pinning for that page, which would be picked up by the logic that controls whether panels should be collapsed or not.

**Comment by dannyhope** [comment]
Sweet!

Just to check that I’ve understood: it would default to automatically collapsing unless you press the pin in the extension popup?

**Comment by lnikkila** [comment]
Yes, but only if you’ve checked the box in the extension settings to enable that behaviour. Here are a few screen shots. There will be more settings and there are no pins yet.

![screenshot 2015-02-15 01 45 50](https://cloud.githubusercontent.com/assets/1291143/6201478/092525fc-b4b5-11e4-8655-42fbd264e6a1.png)

![screenshot 2015-02-15 01 45 33](https://cloud.githubusercontent.com/assets/1291143/6201477/092477a6-b4b5-11e4-8d34-5fbb30b59455.png)

**Comment by dannyhope** [comment]
Ah I see, cool

**Comment by lnikkila** [comment]
The option is now there, but pinning is still missing. Turns out that tabs that are in panel windows are not visible via the API.

I don’t think it’s going to make it into the next release, but I’ll create a new issue for it. Shouldn’t take much longer!
