### ISSUE TITLE
Keyboard shortcut for minimising panels

### ISSUE THREAD

**Issue by dannyhope** [lnikkila/chrome-panel-tabs#17]
Perhaps there could be a keyboard shortcut for minimising panels, since there seems to be simple way of them minimising automatically ( #15 ).

cmd-m, perhaps?

**Comment by lnikkila** [comment]
Good news! It looks like ⌘M works already; the panel just needs to be focused.

This bodes well for #15 since Chrome seems to implement window states for panels.

**Comment by dannyhope** [comment]
Sweet :+1:
