### ISSUE TITLE
Compatibility with website

### ISSUE THREAD

**Issue by orschiro** [lnikkila/chrome-panel-tabs#20]
Dear @lnikkila,

Thank you very much for your extension! 

I tried using it for the following website featuring a news livestream: http://www.tagesschau.de/multimedia/livestreams/index.html

The website properly opens in a tab but the video is not played. Does it work for you?

Thankfully,

Robert

**Comment by lnikkila** [comment]
Hi Robert, yes, the video plays for me.

Is Chrome blocking plugins on that page? You can check this at chrome://settings/content. Please ensure that it’s set to “Run automatically.”

![screenshot 2015-02-10 07 29 06](https://cloud.githubusercontent.com/assets/1291143/6122679/726670c8-b0f7-11e4-87c0-d1f39d5498d7.png)

If that doesn’t work, can you also provide me your user agent string by going to [this page](http://www.whatsmyua.com) and copying the output here.

**Comment by orschiro** [comment]
Hi @lnikkila,

Thanks for your help. I realised that the video was not playing due to the extension `FlashControl` which seems to block the video despite having the website set on the whitelist.

**Comment by lnikkila** [comment]
Good that it worked!
