### ISSUE TITLE
Resizing panels does not work correctly on Chrome OS

### ISSUE THREAD

**Issue by andmalc** [lnikkila/chrome-panel-tabs#21]
I use the Cloud9 online code editor on a Chromebook.  A panel works nicely for this because the bookmarks and address bars are hidden and the program icon at the bottom right makes it easy to quickly minimize the window while reading documentation.   However the panel is somewhat small on an 11" screen.  Any chance of making the size adjustable?

**Comment by lnikkila** [comment]
Hmm, maybe Chrome OS has some additional restrictions; panels should be resizeable by dragging on their corners. Could you make extra sure before I set up a Chromium OS virtual machine?

**Comment by andmalc** [comment]
OK, small correction: the window is resizable but only to reduce its size.
It won't expand beyond its initial size.

To compare I also tried this with Chrome on Linux and yes, the panel is
fully resizable there.

**Comment by lnikkila** [comment]
Thanks!

Since Chrome handles all window management for panels, it might be that this limitation is hard-coded into it. I’ll see if I can tweak some attributes so that they’ll resize properly.

If that doesn’t work, your best bet is to file a bug report (using your Chrome OS environment) at https://crbug.com/new. I don’t think this is supposed to happen. If you do file an issue, please link to it here so that I can star it and others can see it too.

**Comment by andmalc** [comment]
OK, let me know when you've made your changes and I'll test it out.

I searched for an existing bug for this - didn't see one.

**Comment by lnikkila** [comment]
I downloaded a build of Chromium OS and managed to replicate the bug.

Unfortunately there’s nothing I can do on my side. Trying to set panel dimensions is ignored as it is on other platforms as well.

I’d appreciate it if you filed a bug report for this. I think creating it with your environment details is more convincing than with mine; I used an unofficial build. A video of the current behaviour might be useful too. I captured [this short video](https://drive.google.com/file/d/0B9UscY63JkymZFZaV2dybnFLTHc/view) that you could link to the report.

If it’s useful, the build that’s used in the video is:
```
Chromium 40.0.2214.94 (Platform 6457.89.2015_02_02_0532 (Developer Build - nhiraya) developer-build amd64-generic)
```

It was the only one I could find that was recent enough and worked with VirtualBox. [It can be downloaded from this Japanese site.](http://www.canal.mokuren.ne.jp/ChromiumOS/)

**Comment by andmalc** [comment]
Sorry, totally forgot about this.  I'll file the bug and get you the link.

**Comment by lnikkila** [comment]
That’s alright, I’ll reopen this for better visibility.

**Comment by andmalc** [comment]
Here's your bug report: https://code.google.com/p/chromium/issues/detail?id=463934

Reclosing this issue.  Thanks again.

**Comment by lnikkila** [comment]
Thanks! I’ll keep an eye on that issue.
