### ISSUE TITLE
Stay on top even when panel is not docked?

### ISSUE THREAD

**Issue by clkao** [lnikkila/chrome-panel-tabs#23]
This might be panel restrictions, but it seems if you move the panel out of the bottom dock, it no longer stays on top over other windows.

**Comment by lnikkila** [comment]
Yes this is a known issue. It’s due to how Chrome handles panels; unfortunately there’s no way for extensions to change it.

You could open an issue over at Chrome’s bug tracker: https://crbug.com/new. If you do, please link to it here!

**Comment by lnikkila** [comment]
See #4 for further discussion! :)
