### ISSUE TITLE
Option to hide the context menu item

### ISSUE THREAD

**Issue by tophf** [lnikkila/chrome-panel-tabs#24]
When a user has several/many extensions, each of them feels obliged to add something to the browser context menu, so having an option to control this behavior is beneficial to anyone who likes to keep the menu tidy and compact, because Chrome lacks a Firefox-like addon interface to customize menus.

**Comment by lnikkila** [comment]
I agree that this is definitely a must have. An options UI is almost ready, so I’ll just add this there. Thanks!

**Comment by tophf** [comment]
That options UI is certainly cool, but wouldn't it be reasonable (or maybe even desirable, dunno, haven't read Chrome extension dev guidelines) to also provide a standard options page accessible from the Chrome extensions page?

**Comment by lnikkila** [comment]
Yes, this should be available in the next release. The options tab is just another HTML page that I can reuse on the extensions page. Thanks!
