### ISSUE TITLE
file upload doesn't work in panel

### ISSUE THREAD

**Issue by clkao** [lnikkila/chrome-panel-tabs#28]
Like this very page (opening github issue), clicking file attachment does nothing.

**Comment by lnikkila** [comment]
Confirmed, good catch!

This is a Chrome bug. I’ll submit an issue soon and link to it here.

**Comment by lnikkila** [comment]
See https://crbug.com/463367

**Comment by mehmetakiftutuncu** [comment]
I noticed this while using WhatsApp Web as well.

**Comment by lnikkila** [comment]
In the meantime, a workaround is to drag and drop a file onto the upload button.
