### ISSUE TITLE
1 second delay with black background while opening a panel

### ISSUE THREAD

**Issue by tophf** [lnikkila/chrome-panel-tabs#31]
* Chrome 42-43, a new clean profile with just the PanelTabs extension installed.
* Open a moderately complex page like https://github.com/explore and convert it to a panel via hotkey
* For almost 1 second the panel will have a black background and it looks like nothing happens

**Comment by lnikkila** [comment]
Thanks for the report!

This seems like a Chrome bug since Panel Tabs doesn’t touch the contents of the panel. You should report it at https://crbug.com/new.

After reporting, please link to the bug report here for better visibility.

**Comment by tophf** [comment]
[crbugrep](https://code.google.com/p/chromium/issues/detail?id=467359)

**Comment by lnikkila** [comment]
Thank you! Starred. :star2:
