### ISSUE TITLE
Missing icon in Plank dock on Linux

### ISSUE THREAD

**Issue by orschiro** [lnikkila/chrome-panel-tabs#36]
Dear @lnikkila,

Just a cosmetic issue, yet I wanted to make you aware of it. 

Panel Tabs only displays a generic icon in Plank dock on Linux elementaryOS.

![image](https://cloud.githubusercontent.com/assets/170947/6766785/b06eed3c-d014-11e4-890a-cb5c48047aa2.png)

Let me know if I can help you with more debug information!

Robert

**Comment by lnikkila** [comment]
Hmm, this looks like a Chrome bug. Could you submit it to the upstream bug tracker at https://crbug.com/new and then link to the bug report here for better visibility?

**Comment by orschiro** [comment]
I just did so. Thanks for your advice!

https://code.google.com/p/chromium/issues/detail?id=469453&thanks=469453&ts=1426974546

**Comment by lnikkila** [comment]
Thanks! I’ll keep an eye on that.
