### ISSUE TITLE
Panels stop auto-collapsing after a while

### ISSUE THREAD

**Issue by caeldom** [lnikkila/chrome-panel-tabs#38]
I have no idea exactly how to reproduce this. After ticking Collapse defocused panels option, I've noticed after some time (like 5 mins) panels will just refuse to auto-collapse. I go back to the options tab in the extension overlay (without changing anything), and immediately all panels will behave as normal. Then after some time again, if I refocus on the panel, it will open, then I click away and it will stay open.

**Comment by lnikkila** [comment]
Looks like options aren’t being re-read when Chrome restores a suspended event page. Should be an easy fix!

**Comment by lnikkila** [comment]
Fixed in the next update that should hit your browser soon!

**Comment by caeldom** [comment]
Awesome! thanks :) :+1:
