### ISSUE TITLE
Open bookmarks in new panel

### ISSUE THREAD

**Issue by caeldom** [lnikkila/chrome-panel-tabs#39]
Extending the feature in #37 , can this be added to bookmarks as well? ie Right-click a bookmark to bring up the same option. Additionally, a way to set a specific bookmark so they always open in a new panel? Thanks!

**Comment by lnikkila** [comment]
Sounds easy enough, I’ll probably take a stab at it next weekend. For the second part, take a look at #16. I’m still figuring out how to implement it in a neat way.

**Comment by lnikkila** [comment]
Actually, now that I read my comments on #16 again, I found that a bookmark context menu is still impossible to implement. Boo.

Feel free to hop in the discussion over there, though. I’ll close this as a duplicate.
